In [2]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
my_list

[1, 2, 3, 4]

In [4]:
np.array(my_list)

array([1, 2, 3, 4])

In [7]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methodes

## arrange

### Return evently spaced values within a given interval

In [11]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### zeros and ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

### Return evenly space number over a specific interval
`Used primarily to normalize the data

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
`Creates an identity matrix


In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [17]:
np.random.rand(2)

array([0.52180256, 0.49201914])

In [18]:
np.random.rand(5,5)

array([[0.80108343, 0.11353074, 0.60566603, 0.09774891, 0.68298022],
       [0.15452357, 0.22833527, 0.8237464 , 0.43002439, 0.3000358 ],
       [0.91335116, 0.91498613, 0.71596028, 0.0109224 , 0.76192803],
       [0.96130883, 0.18151126, 0.55144137, 0.04695674, 0.89878367],
       [0.62042456, 0.06480859, 0.74899596, 0.86801032, 0.28047832]])

### randn

### Return a sample from the "Standard Normal" distribution.

In [19]:
np.random.randn(5,5)

array([[-1.78303209, -0.70759329,  0.60754582,  0.72312584, -0.16650121],
       [-2.61621028,  0.34290486, -0.38346288, -0.656423  ,  1.54290488],
       [ 0.5448264 , -0.14774914,  0.90684603,  0.2761604 , -0.20331603],
       [ 1.41802643, -0.08237022,  1.4241336 ,  1.54071796, -0.7020407 ],
       [ 0.72158238, -0.92993986, -1.28439081,  0.60840381,  0.03047484]])

### randint
### Return random integers from low (inclusive) to high (exclusive)

In [20]:
np.random.randint(1,100)

88

In [29]:
arr = np.random.randint(1,100,10)

In [31]:
arr.shape

(10,)

In [33]:
arr.reshape(5,2)

array([[45, 84],
       [44, 88],
       [19, 95],
       [12, 44],
       [88, 86]])

In [34]:
arr.dtype

dtype('int32')

### max, min, argmax, argmin

In [36]:
arr

array([45, 84, 44, 88, 19, 95, 12, 44, 88, 86])

In [37]:
arr.max()

95

In [38]:
arr.argmax()

5

In [39]:
arr.min()

12

In [40]:
arr.argmin()

6

# Numpy Indexing and Selection

In [4]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [5]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
# indexing Row
arr_2d[1][0]

20

In [8]:
# format : arr_2d[row][col] or arr_2d[row,col]
arr_2d[1][0]

20

In [9]:
arr_2d[1,0]

20

In [10]:
# slicing
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [11]:
arr_2d > 20

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [12]:
arr_2d[arr_2d>20]

array([25, 30, 35, 40, 45])

In [14]:
bool_arr = arr_2d > 20
bool_arr

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [15]:
arr_2d + arr_2d 

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
arr_2d * np.eye(3)

array([[ 5.,  0.,  0.],
       [ 0., 25.,  0.],
       [ 0.,  0., 45.]])

In [17]:
np.max(arr_2d)

45

In [18]:
np.log(arr_2d)

array([[1.60943791, 2.30258509, 2.7080502 ],
       [2.99573227, 3.21887582, 3.40119738],
       [3.55534806, 3.68887945, 3.80666249]])

In [19]:
np.sin(arr_2d)

array([[-0.95892427, -0.54402111,  0.65028784],
       [ 0.91294525, -0.13235175, -0.98803162],
       [-0.42818267,  0.74511316,  0.85090352]])

In [20]:
# Sum by row
arr_2d.sum(axis=1)

array([ 30,  75, 120])

In [21]:
# Sum by column
arr_2d.sum(axis=0)

array([60, 75, 90])